# user-service-dev.yml

sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"aaa\",\"password\":\"111\"}]"

spring:
  application:
    name: user-service
  # 不允许配置中心的文件覆盖项目的配置，防止将启动端口信息覆盖
  cloud:
    config:
      override-none: true
    
server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka      #多机容灾可以部署多地     beijing   wuhan等等
      #beijing: http://xxxxxxx/xxx
      #单机只能写defaultZone
      
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
